# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 548b2057083ac123f5cdf337fc861dbac8a4f75235f61b712db8108a3fd0a522f60ed40b327e6375fb2885ff01bfb78640b94d1ae0e3210e0a1011d563cd81f8

test:
  secret_key_base: 9f98a2ef75caa74226df36800130db2a754c96263fba1869f89ab02288743e376bd47ac79e24767e4308f43cd11125512f2982d67369d26afbdf5359c486ac7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
